title: Rauksorg Rulebook
author: Quentin Constant
url: https://rauksorg.github.io/Rauksorg-Rulebook/
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  permalink: pretty
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

remote_theme: abhinavs/moonwalk
theme_config:
  appearance: "dark"
  appearance_toggle: true
  show_perso: true
  home:
    title_perso: Le Personnage
    title_action: Les Actions
    title_scenar: Le Scénario
